[custom]


; ===== 节点分组 =====

;策略组定义

custom_proxy_group=🍎美国节点`select`(?=.*(ua))
custom_proxy_group=🐬香港节点`select`(?=.*(ndd))
custom_proxy_group=🎯默认代理`select`ndd`[]ua
custom_proxy_group=🤖AI服务`select`ua`[]默认代理
custom_proxy_group=🍃流媒体`select`ua`[]默认代理
custom_proxy_group=🚀开发服务`select`ua`[]默认代理

; ===== 分流规则 =====

; 国内直连
ruleset=DIRECT,[]GEOIP,CN

;规则集定义


; AI服务
ruleset=🤖AI服务,[]DOMAIN-SUFFIX,openai.com
ruleset=🤖AI服务,[]DOMAIN-SUFFIX,chatgpt.com
ruleset=🤖AI服务,[]DOMAIN-SUFFIX,anthropic.com
ruleset=🤖AI服务,[]DOMAIN-SUFFIX,claude.ai

; Google 系
ruleset=🐸 开发服务,[]DOMAIN-SUFFIX,google.com
ruleset=🐸 开发服务,[]DOMAIN-SUFFIX,youtube.com
ruleset=🐸 开发服务,[]DOMAIN-SUFFIX,gstatic.com
ruleset=🐸 开发服务,[]DOMAIN-SUFFIX,googleapis.com

; Telegram
ruleset=📲 开发服务,[]DOMAIN-SUFFIX,telegram.org
ruleset=📲开发服务,[]DOMAIN-SUFFIX,t.me

; 流媒体
ruleset=🍃流媒体,[]DOMAIN-SUFFIX,netflix.com
ruleset=🍃流媒体,[]DOMAIN-SUFFIX,nflxvideo.net
ruleset=🍃流媒体,[]DOMAIN-SUFFIX,disneyplus.com
ruleset=🍃流媒体,[]DOMAIN-SUFFIX,hulu.com
ruleset=🍃流媒体,[]DOMAIN-SUFFIX,hbomax.com

; 美国IP
ruleset=美国节点,[]GEOIP,US

; 最终默认
final=默认代理

enable_rule_generator=true
overwrite_original_rules=true


